active_personality_id: -1
audio_in_language: en-US
audio_out_voice: English United States
audio_pitch: 1
auto_save: false
auto_update: false
binding_name: gptq
ctx_size: 4096
data_vectorization_activate: true
data_vectorization_build_keys_words: false
data_vectorization_chunk_size: 512
data_vectorization_method: ftidf_vectorizer
data_vectorization_nb_chunks: 2
data_vectorization_overlap_size: 128
data_vectorization_save_db: false
data_visualization_method: PCA
db_path: /mnt/data1/2023/08/02/ggml/data/database.db
debug: true
discussion_prompt_separator: '!@>'
enable_gpu: true
host: 0.0.0.0
model_name: llama2-7b-chat-codeCherryPop-qLoRA-GPTQ
n_predict: 2056
n_threads: 8
override_personality_model_parameters: true
#personalities: ["job/lobbyist_ai"]
personalities: ["generic/tree_of_thoughts"]
port: 9600
repeat_last_n: 40
repeat_penalty: 1.2
seed: 777
temperature: 4.3
top_k: 250
top_p: 0.95
use_files: true
use_user_name_in_discussions: false
user_avatar: default_user.svg
user_description: ''
user_name: user
version: 21
